version: "3"

services:
  basic-server:
    build: ./
    container_name: basic-server
    restart: unless-stopped:0
    links:
      - mongodb:mongodb
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_USER=root
      - MONGO_PWD=rootPass2ab4e199
      - MONGO_AUTH_SOURCE=admin
    ports:
      - "3001:3001"
    command:
      sh -c 'npm i && npm run prod'
    expose:
      - 3001
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  mongodb:
    image: mongo:latest
    container_name: basic-server-mongodb
    restart: unless-stopped:0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootPass2ab4e199
      - MONGO_INITDB_ROOT_DATABASE=admin
    expose:
      - 27017
    ports:
      - "27017:27017"
    command: mongod --auth
