version: "3"

services:
  basic-server:
    build: ./
    container_name: basic-server
    restart: unless-stopped:0
    ports:
      - "3001:3001"
    command:
      sh -c 'npm i && npm run prod'
    expose:
      - 3001
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
